apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
  labels:
    app: notification-service
spec:
  replicas: 2 # Kita suruh Kubernetes menjalankan 2 copy aplikasi biar aman
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        # Nanti akun dockerhub disesuaikan dengan akunmu
        image: kingdil/satset-notification:latest 
        ports:
        - containerPort: 8088 # Ini port asli dari main.go user_service

---

apiVersion: v1
kind: Service
metadata:
  name: notification-service # Nama ini yang akan dipanggil oleh pintu masuk (Ingress)
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 80         # Port internal Kubernetes
      targetPort: 8088 # Diarahkan ke port aplikasi Go-mu